# version: '3.8'
# services:  
#   api:    
#     build: ./api    
#     container_name: api_backend    
#     ports:      
#       - '4000:4000'    
#     volumes:     
#       - ./api:/app      
#       - ./app/node_modules
version: '3.8'
services:
  frontend:
    build: ./path-to-your-frontend-folder
    ports:
      - "3000:3000"
    volumes:
      - ./path-to-your-frontend-folder:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
